/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.login;

import java.awt.Color;

/**
 *
 * @author Rubén Sosa
 */
public class Boneless extends javax.swing.JFrame {

    /**
     * Creates new form CrearPedido
     */
    private boolean bbqTxtClick = false;
    private boolean bbpTxtClick = false;
    private boolean picTxtClick = false;
    private boolean tamTxtClick = false;
    private boolean manTxtClick = false;
    public Boneless() {
        initComponents();
        this.setExtendedState(this.MAXIMIZED_BOTH);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lbMenu = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        bbqBtn = new javax.swing.JPanel();
        bbqTxt = new javax.swing.JLabel();
        bbpBtn = new javax.swing.JPanel();
        bbpTxt = new javax.swing.JLabel();
        picBtn = new javax.swing.JPanel();
        picTxt = new javax.swing.JLabel();
        tamBtn = new javax.swing.JPanel();
        tamTxt = new javax.swing.JLabel();
        manBtn = new javax.swing.JPanel();
        manTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setPreferredSize(new java.awt.Dimension(325, 680));

        jLabel1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        jLabel1.setText("Pedido");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(158, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(156, 156, 156))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));

        lbMenu.setBackground(new java.awt.Color(255, 255, 255));
        lbMenu.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        lbMenu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/regresar.png"))); // NOI18N
        lbMenu.setText("CREAR PEDIDO");
        lbMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbMenuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbMenuMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/logo.png"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        jLabel20.setText("Salsas");

        bbqBtn.setBackground(new java.awt.Color(255, 255, 255));
        bbqBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        bbqBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        bbqTxt.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        bbqTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bbqTxt.setText("BBQ");
        bbqTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bbqTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bbqTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bbqTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout bbqBtnLayout = new javax.swing.GroupLayout(bbqBtn);
        bbqBtn.setLayout(bbqBtnLayout);
        bbqBtnLayout.setHorizontalGroup(
            bbqBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bbqTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        bbqBtnLayout.setVerticalGroup(
            bbqBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bbqTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bbpBtn.setBackground(new java.awt.Color(255, 255, 255));
        bbpBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        bbpBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        bbpTxt.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        bbpTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bbpTxt.setText("BBQ PICOSA");
        bbpTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bbpTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bbpTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bbpTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout bbpBtnLayout = new javax.swing.GroupLayout(bbpBtn);
        bbpBtn.setLayout(bbpBtnLayout);
        bbpBtnLayout.setHorizontalGroup(
            bbpBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bbpTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        bbpBtnLayout.setVerticalGroup(
            bbpBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bbpTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        picBtn.setBackground(new java.awt.Color(255, 255, 255));
        picBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        picBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        picTxt.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        picTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        picTxt.setText("PICOSA");
        picTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                picTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                picTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                picTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout picBtnLayout = new javax.swing.GroupLayout(picBtn);
        picBtn.setLayout(picBtnLayout);
        picBtnLayout.setHorizontalGroup(
            picBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(picTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        picBtnLayout.setVerticalGroup(
            picBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(picTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tamBtn.setBackground(new java.awt.Color(255, 255, 255));
        tamBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        tamBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tamTxt.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        tamTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tamTxt.setText("TAMARINDO HAB");
        tamTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tamTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tamTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                tamTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout tamBtnLayout = new javax.swing.GroupLayout(tamBtn);
        tamBtn.setLayout(tamBtnLayout);
        tamBtnLayout.setHorizontalGroup(
            tamBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tamTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        );
        tamBtnLayout.setVerticalGroup(
            tamBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tamTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        manBtn.setBackground(new java.awt.Color(255, 255, 255));
        manBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        manBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        manTxt.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        manTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manTxt.setText("MANGO HAB");
        manTxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manTxtMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                manTxtMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                manTxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout manBtnLayout = new javax.swing.GroupLayout(manBtn);
        manBtn.setLayout(manBtnLayout);
        manBtnLayout.setHorizontalGroup(
            manBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
        );
        manBtnLayout.setVerticalGroup(
            manBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(manTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(150, 150, 150)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(bbqBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(bbpBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(picBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(tamBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(manBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(407, 407, 407)
                        .addComponent(jLabel20)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69)
                .addComponent(jLabel20)
                .addGap(81, 81, 81)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(bbpBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(picBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bbqBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tamBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(manBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(267, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuMouseClicked
        CrearPedido cp = new CrearPedido();
        cp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbMenuMouseClicked

    private void lbMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuMouseEntered
        jPanel3.setBackground(Color.orange);
    }//GEN-LAST:event_lbMenuMouseEntered

    private void lbMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbMenuMouseExited
        jPanel3.setBackground(new Color(247,148,29));
    }//GEN-LAST:event_lbMenuMouseExited

    private void bbqTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbqTxtMouseClicked
        // TODO add your handling code here:
        bbqTxtClick = true;
        bbqBtn.setBackground(new Color(247,148,29));
        bbpBtn.setBackground(Color.white);
        picBtn.setBackground(Color.white);
        tamBtn.setBackground(Color.white);
        manBtn.setBackground(Color.white);
    }//GEN-LAST:event_bbqTxtMouseClicked

    private void bbqTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbqTxtMouseEntered
        // TODO add your handling code here:
        if(!bbqTxtClick){
            bbqBtn.setBackground(new Color(247,148,29));
        }
    }//GEN-LAST:event_bbqTxtMouseEntered

    private void bbqTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbqTxtMouseExited
        // TODO add your handling code here:
        if(!bbqTxtClick){
            bbqBtn.setBackground(Color.white);
        }
    }//GEN-LAST:event_bbqTxtMouseExited

    private void bbpTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbpTxtMouseClicked
        // TODO add your handling code here:
        bbpTxtClick = true;
        bbpBtn.setBackground(new Color(247,148,29));
        bbqBtn.setBackground(Color.white);
        picBtn.setBackground(Color.white);
        tamBtn.setBackground(Color.white);
        manBtn.setBackground(Color.white);
    }//GEN-LAST:event_bbpTxtMouseClicked

    private void bbpTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbpTxtMouseEntered
        // TODO add your handling code here:
        if(!bbpTxtClick) {
            bbpBtn.setBackground(new Color(247,148,29));
        }
    }//GEN-LAST:event_bbpTxtMouseEntered

    private void bbpTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bbpTxtMouseExited
        // TODO add your handling code here:
        if(!bbpTxtClick) {
            bbpBtn.setBackground(Color.white);
        }
    }//GEN-LAST:event_bbpTxtMouseExited

    private void picTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_picTxtMouseClicked
        // TODO add your handling code here:
        picTxtClick = true;
        picBtn.setBackground(new Color(247,148,29));
        bbqBtn.setBackground(Color.white);
        bbpBtn.setBackground(Color.white);
        tamBtn.setBackground(Color.white);
        manBtn.setBackground(Color.white);
    }//GEN-LAST:event_picTxtMouseClicked

    private void picTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_picTxtMouseEntered
        // TODO add your handling code here:
        if(!picTxtClick) {
            picBtn.setBackground(new Color(247,148,29));
        }
    }//GEN-LAST:event_picTxtMouseEntered

    private void picTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_picTxtMouseExited
        // TODO add your handling code here:
         if(!picTxtClick) {
            picBtn.setBackground(Color.white);
        }
    }//GEN-LAST:event_picTxtMouseExited

    private void tamTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tamTxtMouseClicked
        // TODO add your handling code here:
        tamTxtClick = true;
        tamBtn.setBackground(new Color(247,148,29));
        bbqBtn.setBackground(Color.white);
        bbpBtn.setBackground(Color.white);
        picBtn.setBackground(Color.white);
        manBtn.setBackground(Color.white);
    }//GEN-LAST:event_tamTxtMouseClicked

    private void tamTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tamTxtMouseEntered
        // TODO add your handling code here:
        if(!tamTxtClick) {
            tamBtn.setBackground(new Color(247,148,29));
        }
    }//GEN-LAST:event_tamTxtMouseEntered

    private void tamTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tamTxtMouseExited
        // TODO add your handling code here:
        if(!tamTxtClick) {
            tamBtn.setBackground(Color.white);
        }
    }//GEN-LAST:event_tamTxtMouseExited

    private void manTxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manTxtMouseClicked
        // TODO add your handling code here:
        manTxtClick = true;
        manBtn.setBackground(new Color(247,148,29));
        bbqBtn.setBackground(Color.white);
        bbpBtn.setBackground(Color.white);
        tamBtn.setBackground(Color.white);
        picBtn.setBackground(Color.white);
    }//GEN-LAST:event_manTxtMouseClicked

    private void manTxtMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manTxtMouseEntered
        // TODO add your handling code here:
        if(!manTxtClick) {
            manBtn.setBackground(new Color(247,148,29));
        }
    }//GEN-LAST:event_manTxtMouseEntered

    private void manTxtMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manTxtMouseExited
        // TODO add your handling code here:
        if(!manTxtClick) {
            manBtn.setBackground(Color.white);
        }
    }//GEN-LAST:event_manTxtMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Boneless.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Boneless.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Boneless.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Boneless.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Boneless().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bbpBtn;
    private javax.swing.JLabel bbpTxt;
    private javax.swing.JPanel bbqBtn;
    private javax.swing.JLabel bbqTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbMenu;
    private javax.swing.JPanel manBtn;
    private javax.swing.JLabel manTxt;
    private javax.swing.JPanel picBtn;
    private javax.swing.JLabel picTxt;
    private javax.swing.JPanel tamBtn;
    private javax.swing.JLabel tamTxt;
    // End of variables declaration//GEN-END:variables
}
